// <auto-generated />
namespace ImporterData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addchange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addchange));
        
        string IMigrationMetadata.Id
        {
            get { return "202210111016276_add-change"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
